### ISSUE TITLE
Private Repositoryを変更するとPush Notificationが強制的にオンになる

### ISSUE THREAD

**Issue by kenjiskywalker** [ishkawa/GHFSupport#1]
Private Repositoryの状態を変更すると
Push Notificationをオフにしていてもオンになります。
Private Repositoryをオフにする場合も、オンにする場合もPush Notificationはオンになります。

**Comment by ishkawa** [comment]
報告ありがとうございます。
現在1.0.1を申請中なので、1.0.2で修正する予定です。

**Comment by ishkawa** [comment]
1.1.0で修正しました！
