### ISSUE TITLE
未読バッジが消えない

### ISSUE THREAD

**Issue by somtd** [ishkawa/GHFSupport#2]
未読バッジはどの数をカウントしてますか？

**Comment by ishkawa** [comment]
GitHubの未読数と同じ数(上限あり)を出しているつもりでした。
Mark everything as readボタンを押してからGHFeedを開いても未読バッジは残りますか？

![6205b254a8ec54aac3a6367bc774b133](https://f.cloud.github.com/assets/966856/1039377/af5c7f44-0f82-11e3-86de-7729b5f994d5.png)

**Comment by somtd** [comment]
消えました！ありがとうございます。

**Comment by ishkawa** [comment]
:beer:

**Comment by mipstian** [comment]
Hi!

I'm having the same issue (badge number stuck at 1), but marking everything as read on github.com didn't fix it. I did mark everything as read on all repos that had notifications, even if GH showed no unread ones to begin with.

![screen shot 2015-02-11 at 10 39 54 am](https://cloud.githubusercontent.com/assets/421341/6144656/55b325c8-b1da-11e4-9f56-a1c2703034e1.png)

What can I do to troubleshoot?

P.s. sorry, my Japanese is only good enough to understand the above :)

**Comment by ishkawa** [comment]
Hi, thanks for reporting.

Some error might occur on sending new badge to your iOS device. I will investigate this issue and let you know when it is fixed.

**Comment by mipstian** [comment]
For what it's worth, I received two identical push notifications when you replied to this issue (weird? maybe one for the reopening and one for the reply, idk), and opening the notification cleared the badge in GHFeed. So it looks like the problem eventually fixes itself when a new notification arrives.

Oh I forgot: the blue dot on the notification icon was also present when the badge was stuck to "1".

Thanks and good luck with debugging!

**Comment by ishkawa** [comment]
It makes sense to me. I will fix iOS app this weekend and submit it to App Store.

**Comment by mipstian** [comment]
ありがとうございます！

**Comment by ishkawa** [comment]
Sorry for the late response. New version of GHFeed (2.1.2) is now available, and this issues is fixed in it.

**Comment by mipstian** [comment]
Yeah I saw, thanks! With this new version I still had the badge linger for a bit after reading an issue, but the next time I opened the app the badge cleared, so it's no longer "stuck". Love this app!

**Comment by ishkawa** [comment]
Thanks! I noticed the issue you mention after release. It will be fixed next version!

**Comment by mipstian** [comment]
Cool! Just a minor inconvenience anyway, no big deal.
