### ISSUE TITLE
Releaseの遷移先がAPI URLのままになっている

### ISSUE THREAD

**Issue by azu** [ishkawa/GHFSupport#3]
![Alt text](https://monosnap.com/image/DyxJysNqIsz16WvMNMiQ5onWj.png)

NewsFeedにReleaseが来た際に遷移先が

https://api.github.com/repos/facebook/xctool/releases/v0.1.10

のようなAPIのURLで404となっています。

**Comment by ishkawa** [comment]
報告ありがとうございます。見落としてました。
次の次のバージョン(1.1.0)で修正します。

**Comment by ishkawa** [comment]
1.1.0で修正したつもりだったんですが、該当のtagに飛ぶようになってしまっていたので、1.2.0でリリースページに飛ぶように変更します。
