### ISSUE TITLE
Pull Requestのコードコメントがnullと表示される

### ISSUE THREAD

**Issue by okuryu** [ishkawa/GHFSupport#4]
Pull Requestの差分コードにコメントした際のフィードの番号がnullと表示されます。

![sep 07 9 17 09 am](https://f.cloud.github.com/assets/34588/1100311/96b7676e-1753-11e3-8613-1b39515fae39.png)

**Comment by ishkawa** [comment]
ご報告ありがとうございます。
次のバージョンで修正します。

**Comment by ishkawa** [comment]
1.1.0で修正しました。
ご報告ありがとうございました。
