### ISSUE TITLE
iOS6.1.3(iPhone4S)でPush NotificationもBadgeも表示されない

### ISSUE THREAD

**Issue by sharl** [ishkawa/GHFSupport#5]
右上の例のアレは青くなってるんですが、まったく表示されません。

**Comment by ishkawa** [comment]
遅くなってしまい、すみません。

サーバーに通知用の情報が登録されていないのかもしれません。
iOSの設定.app -> 通知 -> GHFeedからサウンドかバッジのどちらかがオンになっていることを確認の上、
GHFeed内の設定画面のPush Notificationを一旦オフにしてから再度オンにしてみていただけますか？

**Comment by sharl** [comment]
Push Notificaion OFF→ONで表示されるようになりました。
ご確認ありがとうございました。
