### ISSUE TITLE
Wikiの更新フィードが正しく表示されない

### ISSUE THREAD

**Issue by okuryu** [ishkawa/GHFSupport#6]
![img_0082](https://f.cloud.github.com/assets/34588/1122366/fa5de82c-1ad9-11e3-9676-1ccbbc7bcf27.PNG)

**Comment by ishkawa** [comment]
ご連絡ありがとうございます！
次のバージョン(1.1.0)で修正されますのでお待ちください。

**Comment by ishkawa** [comment]
こちらも1.1.0で修正しました。
ご報告ありがとうございました。
